/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "elect.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

outputstruct *
elect_1(inputstruct *argp, CLIENT *clnt)
{
	static outputstruct clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ELECT,
		(xdrproc_t) xdr_inputstruct, (caddr_t) argp,
		(xdrproc_t) xdr_outputstruct, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
