/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ELECT_H_RPCGEN
#define _ELECT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct outputstruct {
	float e;
	float q;
	float i;
	float z;
	float p;
};
typedef struct outputstruct outputstruct;

struct inputstruct {
	float c;
	float v;
	float t;
};
typedef struct inputstruct inputstruct;

#define ELECT_PROG 0x23451111
#define ELCT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ELECT 1
extern  outputstruct * elect_1(inputstruct *, CLIENT *);
extern  outputstruct * elect_1_svc(inputstruct *, struct svc_req *);
extern int elect_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ELECT 1
extern  outputstruct * elect_1();
extern  outputstruct * elect_1_svc();
extern int elect_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_outputstruct (XDR *, outputstruct*);
extern  bool_t xdr_inputstruct (XDR *, inputstruct*);

#else /* K&R C */
extern bool_t xdr_outputstruct ();
extern bool_t xdr_inputstruct ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ELECT_H_RPCGEN */
