/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "elect.h"

outputstruct *
elect_1_svc(inputstruct *argp, struct svc_req *rqstp)
{
	static outputstruct  result;

	// server side calculation code goes here

	result.e = (argp->c*argp->v*argp->v)/2;
	result.q = argp->c*argp->v;
	result.i = result.q/argp->t;
	result.z = argp->v/result.i;
	result.p = (result.e)/argp->t;
	printf("Enery : %4.2f Charge : %4.2f Current : %4.2f Capasitor Reactans : %4.2f Power : %4.2f \n", result.e, result.q, result.i,  result.z, result.p);

	return &result;
}
