/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "elect.h"

bool_t
xdr_outputstruct (XDR *xdrs, outputstruct *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->e))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->q))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->i))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->z))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->p))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_inputstruct (XDR *xdrs, inputstruct *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->c))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->v))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->t))
		 return FALSE;
	return TRUE;
}
